CREATE EXTENSION PGCRYPTO;

CREATE TABLE USERS(
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(100),
	last_name VARCHAR(100),
	email VARCHAR(50),
	password TEXT NOT NULL
)

INSERT INTO users(first_name,last_name,email,password)
VALUES(
'Jhon','Doe','jhindoe@mail.com',crypt('jhonpassword',gen_salt('bf'))
);

select * from users

CREATE TABLE TODO(
	TODO_ID SERIAL PRIMARY KEY,
	TASK_NAME TEXT NOT NULL, 
	DESCRIPTION VARCHAR(100),
	STATUS BOOLEAN, 
	DUE_DATE DATE, 
	USER_ID INT,
	CONSTRAINT fk_todo FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

INSERT INTO TODO (TASK_NAME,DESCRIPTION,STATUS,DUE_DATE,USER_ID)
VALUES(
'TASK','yOU HAVE TO FINISH THE LAST PROJECT','FALSE','2021-08-14',1
);
SELECT * FROM TODO
